### ISSUE TITLE
Update to support F4-based streaming

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/encrypted-stream-name#1]
Currently this code is targeting our DAMS4 file naming conventions. 

We need to update the code to support the F4 binary file path as described in https://github.com/ucsdlib/dams5-cc-pilot/issues/27

**Comment by lsitu** [comment]
@mcritchlow @rstanonik: In dams4, we are encrypted the stream name with three fields (ark, file, and ip) and decoded it for Wowza. While in fedora, binary is stored in pair tree ( 3 level deep) with its MessageDigest (md5) as the file name instead. So to build the stream name for Wowza from a Fedora 4 binary file, we need to specify the media type: mp3, mp4, and flv etc.

How about encrypted the fields like object id, file id, md5, media type (or source file name?), and ip for Fedora 4? I think object id and file id are mainly used for logging reference.

**Comment by lsitu** [comment]
I've added a [PR](https://github.com/ucsdlib/encrypted-stream-name/issues/2) to include object ID, fileset ID, Fedora binary stream name, file name, and request id in the encrypted text, which will allow the Wowza server to load the Videos/Audios from the Fedora binary store.

**Comment by stanonik** [comment]
It will also be necessary to write/modify the wowza module that understands the additional information, so wowza can locate and stream the file.

**Comment by lsitu** [comment]
@stanonik Yes, we need to mount the Fedora binary store to the VM where the Wowza server is running so that the Wowza server can locate the file by the stream name, which is a pair tree structure handled at [line#L286-L294](https://github.com/ucsdlib/encrypted-stream-name/blob/1f0f6d3649d81542b524ffba0515c2b709cd64e5/src/java/edu/ucsd/library/dams/util/EncryptedStreamNameModule.java#L286-L294).
I'll create a PR for ticket https://github.com/ucsdlib/dams5-cc-pilot/issues/43 so that can test the Wowza support later.

**Comment by mcritchlow** [comment]
Going to close this out and we can do more testing when we have a staging environment
